version: '3'  

services:
  db:  
    image: 'postgres:16.3'  
    environment:
      POSTGRES_USER: accounts 
      POSTGRES_PASSWORD: accounts  
      POSTGRES_DB: accounts  
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'  

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
