version: '3'  

services:
  db:  
    image: 'postgres:16.3'  
    environment:
      POSTGRES_USER: accounts 
      POSTGRES_PASSWORD: accounts  
      POSTGRES_DB: accounts  
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'  

volumes:
  pgdata:
  